packages:
  - .
overrides:
  "@next/env": "npm:@varlock/nextjs-integration"
  "dotenv": "npm:varlock"
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
allowBuilds:
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@types/node@25.9.3'
